/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoanRepaymentCalc.Presentation;

import LoanRepaymentCalc.domain.*;
import LoanRepaymentCalc.service.AccountSvcCacheImpl;
import LoanRepaymentCalc.service.IAccountSvc;
import javax.swing.JOptionPane;

/**
 *
 * @author jake
 */
public class CreateLoanUI extends javax.swing.JFrame {
    
    private Account account = null;
    
    public void setAccount(Account account){
        this.account = account;
    }

    /**
     * Creates new form CreateLoanUI
     */
    public CreateLoanUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MLTItleBar = new javax.swing.JLabel();
        loanNameFld = new javax.swing.JTextField();
        CLLoanNameTitle = new javax.swing.JLabel();
        CLLoanTypeTitle = new javax.swing.JLabel();
        CLLoanHolderTitle = new javax.swing.JLabel();
        loanHolderFld = new javax.swing.JTextField();
        CLLoanGroupTitle = new javax.swing.JLabel();
        loanGroupFld = new javax.swing.JTextField();
        CLLoanAmountTitle = new javax.swing.JLabel();
        loanAmountFld = new javax.swing.JTextField();
        CLLoanAPRTitle = new javax.swing.JLabel();
        loanAPRFld = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        amountDescription = new javax.swing.JLabel();
        aprDescrition = new javax.swing.JLabel();
        loanTypeFld = new javax.swing.JTextField();
        typeDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adding A New Loan");

        MLTItleBar.setFont(new java.awt.Font("Lohit Telugu", 1, 48)); // NOI18N
        MLTItleBar.setForeground(new java.awt.Color(0, 204, 0));
        MLTItleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MLTItleBar.setText("Create New Loan");

        loanNameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanNameFldActionPerformed(evt);
            }
        });

        CLLoanNameTitle.setText("Loan Name     :");

        CLLoanTypeTitle.setText("Loan Type      :");

        CLLoanHolderTitle.setText("Loan Holder   :");

        loanHolderFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanHolderFldActionPerformed(evt);
            }
        });

        CLLoanGroupTitle.setText("Loan Group    :");

        loanGroupFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanGroupFldActionPerformed(evt);
            }
        });

        CLLoanAmountTitle.setText("Loan Amount :");

        loanAmountFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmountFldActionPerformed(evt);
            }
        });

        CLLoanAPRTitle.setText("Loan APR       :");

        loanAPRFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAPRFldActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        amountDescription.setText("Loan Amount must be a decimal number GREATER THAN 0.00");

        aprDescrition.setText("APR must also be a decimal number GREATER THAN 0.00");

        typeDescription.setText("Please use Sub, Unsub, or Personal for Loan Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MLTItleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CLLoanNameTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CLLoanTypeTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CLLoanHolderTitle)
                    .addComponent(CLLoanGroupTitle)
                    .addComponent(CLLoanAmountTitle)
                    .addComponent(CLLoanAPRTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typeDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(aprDescrition, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(amountDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loanAmountFld)
                    .addComponent(loanGroupFld, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(loanHolderFld)
                    .addComponent(loanNameFld)
                    .addComponent(loanAPRFld, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loanTypeFld))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MLTItleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLLoanNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLLoanTypeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanTypeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(typeDescription)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLLoanHolderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanHolderFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLLoanGroupTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanGroupFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLLoanAmountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanAmountFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountDescription)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLLoanAPRTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanAPRFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aprDescrition)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loanNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanNameFldActionPerformed

    private void loanHolderFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanHolderFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanHolderFldActionPerformed

    private void loanGroupFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanGroupFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanGroupFldActionPerformed

    private void loanAmountFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmountFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanAmountFldActionPerformed

    private void loanAPRFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAPRFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanAPRFldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Loan loan = new Loan();
        loan.setLoanName(loanNameFld.getText());
        loan.setLoanType(loanTypeFld.getText());
        loan.setLoanHolder(loanHolderFld.getText());
        loan.setLoanGroup(loanGroupFld.getText());
        
        // not sure if this is an ideal setup
        String loanAmt = loanAmountFld.getText();
        String loanAPR = loanAPRFld.getText();
        double lnAmt;
        double lnApr;
        
        try{
            lnAmt = Double.parseDouble(loanAmt);
        }
        catch(NumberFormatException e)
        {
            lnAmt = 0;
        }
           
        try{
            lnApr = Double.parseDouble(loanAPR);
        }
        catch(NumberFormatException e)
        {
            lnApr = 0.0;
        }
        
        loan.setLoanAmount(lnAmt);
        loan.setApr(lnApr);
        
        boolean isValid = loan.validate();
        if(!isValid){
            if(loan.getApr() == 0){
                JOptionPane.showMessageDialog(this, 
                    "APR must be greater than zero",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(loan.getLoanAmount() == 0){
                JOptionPane.showMessageDialog(this, 
                    "Loan Amount must be greater than zero",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(loan.getLoanName() == null){
                JOptionPane.showMessageDialog(this, 
                    "Invalid Loan NAME Please try again!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(loan.getLoanGroup() == null){
                JOptionPane.showMessageDialog(this, 
                    "Invalid Loan GROUP Please try again!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(loan.getLoanHolder() == null){
                JOptionPane.showMessageDialog(this, 
                    "Invalid Loan HOLDER Please try again!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(loan.getLoanType() == null){
                JOptionPane.showMessageDialog(this, 
                    "Invalid Loan Type Please try again!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }
        account.add(loan);
        IAccountSvc impl = AccountSvcCacheImpl.getInstance();
        account = impl.update(account);
        if(account == null){
            JOptionPane.showMessageDialog(this, "There was an error with your" +
                    " Account the Loan was not saved, please try again",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Your Loan has been Saved!");
        
        loanNameFld.setText("");
        loanTypeFld.setText("");
        loanHolderFld.setText("");
        loanGroupFld.setText("");
        loanAmountFld.setText("");
        loanAPRFld.setText("");
        //Passing account back to masterList
        LoanMasterListUI masterList = new LoanMasterListUI();
        masterList.setAccount(account);
        masterList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        LoanMasterListUI masterList = new LoanMasterListUI();
        masterList.setAccount(account);
        masterList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLoanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateLoanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLLoanAPRTitle;
    private javax.swing.JLabel CLLoanAmountTitle;
    private javax.swing.JLabel CLLoanGroupTitle;
    private javax.swing.JLabel CLLoanHolderTitle;
    private javax.swing.JLabel CLLoanNameTitle;
    private javax.swing.JLabel CLLoanTypeTitle;
    private javax.swing.JLabel MLTItleBar;
    private javax.swing.JLabel amountDescription;
    private javax.swing.JLabel aprDescrition;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField loanAPRFld;
    private javax.swing.JTextField loanAmountFld;
    private javax.swing.JTextField loanGroupFld;
    private javax.swing.JTextField loanHolderFld;
    private javax.swing.JTextField loanNameFld;
    private javax.swing.JTextField loanTypeFld;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel typeDescription;
    // End of variables declaration//GEN-END:variables
}
