/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoanRepaymentCalc.Presentation;

import LoanRepaymentCalc.domain.*;
import LoanRepaymentCalc.service.*;
import javax.swing.JOptionPane;


/**
 *
 * @author jake
 */
public class CreateAccountUI extends javax.swing.JFrame {

    /**
     * Creates new form CreatAcctUI
     */
    public CreateAccountUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jFrame1 = new javax.swing.JFrame();
        CATItleBar = new javax.swing.JLabel();
        passwordFld = new javax.swing.JPasswordField();
        verifyPasswordFld = new javax.swing.JPasswordField();
        CAUserTitle = new javax.swing.JLabel();
        CAPass1Title = new javax.swing.JLabel();
        userNameFld = new javax.swing.JFormattedTextField();
        CAPass2Title = new javax.swing.JLabel();
        CAEmailTitle = new javax.swing.JLabel();
        CAEmail2Title = new javax.swing.JLabel();
        verifyEmailFld = new javax.swing.JFormattedTextField();
        emailFld = new javax.swing.JFormattedTextField();
        cancelBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Creation");
        setBounds(new java.awt.Rectangle(0, 0, 1006, 561));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CATItleBar.setFont(new java.awt.Font("Lohit Telugu", 1, 48)); // NOI18N
        CATItleBar.setForeground(new java.awt.Color(0, 204, 0));
        CATItleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CATItleBar.setText("Create Account");
        CATItleBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(CATItleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1006, 101));
        getContentPane().add(passwordFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 199, 322, 40));
        getContentPane().add(verifyPasswordFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 280, 322, 40));

        CAUserTitle.setText("User Name");
        getContentPane().add(CAUserTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 131, 131, -1));

        CAPass1Title.setText("Verify Password");
        getContentPane().add(CAPass1Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 291, 131, 18));

        userNameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFldActionPerformed(evt);
            }
        });
        getContentPane().add(userNameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 119, 322, 40));

        CAPass2Title.setText(" Password ");
        getContentPane().add(CAPass2Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 211, 131, -1));

        CAEmailTitle.setText("Email");
        getContentPane().add(CAEmailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 372, 131, -1));

        CAEmail2Title.setText("Verify Email");
        getContentPane().add(CAEmail2Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 452, 131, -1));

        verifyEmailFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyEmailFldActionPerformed(evt);
            }
        });
        getContentPane().add(verifyEmailFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 440, 322, 40));

        emailFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFldActionPerformed(evt);
            }
        });
        getContentPane().add(emailFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 360, 322, 40));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 506, -1, -1));

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 506, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel1.setText("Your Password Must contain: at least 7 characters, contain one letter and one number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 252, 503, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFldActionPerformed

    private void verifyEmailFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyEmailFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verifyEmailFldActionPerformed

    private void emailFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        LoginUI login = new LoginUI();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        Login login = new Login();
        login.setUserName(userNameFld.getText());
        login.setPassword(new String (passwordFld.getPassword()));
        if(!login.validate()){
            if(login.getPassword() == null){
                JOptionPane.showMessageDialog(this, "Please enter a valid password",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(login.getUserName() == null){
                JOptionPane.showMessageDialog(this, "Please enter a valid Username",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }
        
        String confirmPassword = new String(verifyPasswordFld.getPassword());
        if(!confirmPassword.equals(login.getPassword())){
            JOptionPane.showMessageDialog(this, 
                    "Passwords do not match; try again", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        Account account = new Account();
        account.setEmail(emailFld.getText());
        account.setLogin(login);
        
        String confirmEmail = new String(verifyEmailFld.getText());
        if(!confirmEmail.equals(emailFld.getText())){
            JOptionPane.showMessageDialog(this, 
                    "Email Addresses do not match; try again", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean isValid = account.validate();
        if(!isValid){
            if(account.getEmail() == null)
            JOptionPane.showMessageDialog(this, "Invalid Email",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            AccountSvcCacheImpl impl = AccountSvcCacheImpl.getInstance();
            account = impl.create(account);
            JOptionPane.showMessageDialog(this, "You have Succesfully Created a New Account",
                    "Account Created", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            LoginUI loginUI = new LoginUI();
            loginUI.setVisible(true);
        }
          
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountUI().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CAEmail2Title;
    private javax.swing.JLabel CAEmailTitle;
    private javax.swing.JLabel CAPass1Title;
    private javax.swing.JLabel CAPass2Title;
    private javax.swing.JLabel CATItleBar;
    private javax.swing.JLabel CAUserTitle;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JFormattedTextField emailFld;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passwordFld;
    private javax.swing.JButton submitBtn;
    private javax.swing.JFormattedTextField userNameFld;
    private javax.swing.JFormattedTextField verifyEmailFld;
    private javax.swing.JPasswordField verifyPasswordFld;
    // End of variables declaration//GEN-END:variables
}
