/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoanRepaymentCalc.Presentation;
import LoanRepaymentCalc.domain.*;
import LoanRepaymentCalc.service.AccountSvcCacheImpl;
import LoanRepaymentCalc.service.IAccountSvc;
import javax.swing.JOptionPane;
/**
 *
 * @author jake
 */
public class LoanDetailUI extends javax.swing.JFrame {
    //Needed to pass the account object back and forth to UI
    private Loan loan = null;
    private Account account = null;
    public void setAccount(Account account){
        this.account = account;
    }

    /**OverLoaded Constructor to allow for passing of loan Details
     * Creates new form LoanDetailUI
     * @param loan
     */
    public LoanDetailUI(Loan loan) {
        initComponents();
        this.loan = loan;
        double loanAmount = loan.getLoanAmount();
        String amount = Double.toString(loanAmount);
        double apr = loan.getApr();
        String aprTemp = Double.toString(apr);
        loanNameFld.setText(loan.getLoanName());
        loanHolderFld.setText(loan.getLoanHolder());
        loanTypeFld.setText(loan.getLoanType());
        loanGroupFld.setText(loan.getLoanGroup());
        loanAmountFld.setText(amount);
        loanAPRFld.setText(aprTemp);
    }
    public LoanDetailUI(){
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        LDLoanTypeTitle = new javax.swing.JLabel();
        LDLoanAPRTitle = new javax.swing.JLabel();
        LDLoanHolderTitle = new javax.swing.JLabel();
        loanAPRFld = new javax.swing.JTextField();
        loanHolderFld = new javax.swing.JTextField();
        previousBtn = new javax.swing.JButton();
        LDLoanGroupTitle = new javax.swing.JLabel();
        loanGroupFld = new javax.swing.JTextField();
        LDTItleBar = new javax.swing.JLabel();
        loanNameFld = new javax.swing.JTextField();
        LDLoanNameTitle = new javax.swing.JLabel();
        LDLoanAmountTitle = new javax.swing.JLabel();
        loanAmountFld = new javax.swing.JTextField();
        loanTypeFld = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Details");

        LDLoanTypeTitle.setText("Loan Type      :");

        LDLoanAPRTitle.setText("Loan APR       :");

        LDLoanHolderTitle.setText("Loan Holder   :");

        loanAPRFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAPRFldActionPerformed(evt);
            }
        });

        loanHolderFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanHolderFldActionPerformed(evt);
            }
        });

        previousBtn.setText("Cancel");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        LDLoanGroupTitle.setText("Loan Group    :");

        loanGroupFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanGroupFldActionPerformed(evt);
            }
        });

        LDTItleBar.setFont(new java.awt.Font("Lohit Telugu", 1, 48)); // NOI18N
        LDTItleBar.setForeground(new java.awt.Color(0, 204, 0));
        LDTItleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LDTItleBar.setText("Loan Details");

        loanNameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanNameFldActionPerformed(evt);
            }
        });

        LDLoanNameTitle.setText("Loan Name     :");

        LDLoanAmountTitle.setText("Loan Amount :");

        loanAmountFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmountFldActionPerformed(evt);
            }
        });

        loanTypeFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTypeFldActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Details");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Loan");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LDTItleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(previousBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LDLoanNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LDLoanTypeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LDLoanHolderTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LDLoanGroupTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LDLoanAmountTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LDLoanAPRTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(loanAmountFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loanGroupFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addComponent(loanTypeFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loanNameFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loanAPRFld)
                            .addComponent(loanHolderFld, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(updateBtn)))
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LDTItleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LDLoanNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDLoanTypeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanTypeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDLoanHolderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanHolderFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDLoanGroupTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanGroupFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDLoanAmountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanAmountFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDLoanAPRTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanAPRFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loanAPRFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAPRFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanAPRFldActionPerformed

    private void loanHolderFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanHolderFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanHolderFldActionPerformed

    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        LoanMasterListUI mainUI = new LoanMasterListUI();
        mainUI.setAccount(account);
        mainUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_previousBtnActionPerformed

    private void loanGroupFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanGroupFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanGroupFldActionPerformed

    private void loanNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanNameFldActionPerformed

    private void loanAmountFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmountFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanAmountFldActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null, 
                "Are you sure you would like to DELETE the current Loan?",
                "Yes/No",
                JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION){
            //int num = loan.getId();
            account.getLoans().remove(loan);
            LoanMasterListUI mainUI = new LoanMasterListUI();
            mainUI.setAccount(account);
            mainUI.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

   
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        loan.setLoanName(loanNameFld.getText());
        loan.setLoanType(loanTypeFld.getText());
        loan.setLoanHolder(loanHolderFld.getText());
        loan.setLoanGroup(loanGroupFld.getText());
        String loanAmt = loanAmountFld.getText();
        String loanAPR = loanAPRFld.getText();
        double lnAmt;
        double lnApr;
        
        try{
            lnAmt = Double.parseDouble(loanAmt);
        }
        catch(NumberFormatException e)
        {
            lnAmt = 0;
        }
           
        try{
            lnApr = Double.parseDouble(loanAPR);
        }
        catch(NumberFormatException e)
        {
            lnApr = 0.0;
        }
        
        loan.setLoanAmount(lnAmt);
        loan.setApr(lnApr);
        
        boolean isValid = loan.validate();
        if(!isValid){
            JOptionPane.showMessageDialog(this, 
                    "All Fields must have a proper value"
                            + " Note:APR and Amount must be greater than zero",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        IAccountSvc impl = AccountSvcCacheImpl.getInstance();
        account = impl.update(account);
        if(account == null){
            JOptionPane.showMessageDialog(this, "There was an error with your" +
                    " Account the Loan was not Updated, please try again",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Your Loan has been Updated!");
        LoanMasterListUI mainUI = new LoanMasterListUI();
        mainUI.setAccount(account);
        mainUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void loanTypeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTypeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanTypeFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanDetailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanDetailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanDetailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanDetailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanDetailUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LDLoanAPRTitle;
    private javax.swing.JLabel LDLoanAmountTitle;
    private javax.swing.JLabel LDLoanGroupTitle;
    private javax.swing.JLabel LDLoanHolderTitle;
    private javax.swing.JLabel LDLoanNameTitle;
    private javax.swing.JLabel LDLoanTypeTitle;
    private javax.swing.JLabel LDTItleBar;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField loanAPRFld;
    private javax.swing.JTextField loanAmountFld;
    private javax.swing.JTextField loanGroupFld;
    private javax.swing.JTextField loanHolderFld;
    private javax.swing.JTextField loanNameFld;
    private javax.swing.JTextField loanTypeFld;
    private javax.swing.JButton previousBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
