/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoanRepaymentCalc.Presentation;


import LoanRepaymentCalc.domain.*;

/**
 *
 * @author jake
 */
public class LoanMasterListUI extends javax.swing.JFrame 
{
    
    private Account account = null;
    
    private LoanTableModel model = new LoanTableModel();
    
    public void setAccount(Account account)
    {
        this.account = account;
        model.setLoans(account.getLoans());
    }

    /**
     * Creates new form NewJFrame
     */
    public LoanMasterListUI() 
    {
        initComponents();
        
        loanML.setModel(model);
        
        loanML.addMouseListener(new java.awt.event.MouseAdapter()
        {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                int row = loanML.rowAtPoint(evt.getPoint());
                if (row>=0){
                    Loan loan = model.getLoan(row);
                    // passing value to overridden constructor
                    //also ensuring the account can be transfered back to reopen
                    // the master list on cancel
                    LoanDetailUI LoanDetailUI = new LoanDetailUI(loan);
                    LoanDetailUI.setAccount(account);
                    LoanDetailUI.setVisible(true);
                    LoanMasterListUI.this.setVisible(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MLTItleBar = new javax.swing.JLabel();
        addNewLoan = new javax.swing.JButton();
        MLSortByFld = new javax.swing.JComboBox<>();
        MLSortTitle = new javax.swing.JLabel();
        MLPayBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanML = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your Loan List");

        MLTItleBar.setFont(new java.awt.Font("Lohit Telugu", 1, 48)); // NOI18N
        MLTItleBar.setForeground(new java.awt.Color(0, 204, 0));
        MLTItleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MLTItleBar.setText("Master Loan List");

        addNewLoan.setText("Add New Loan");
        addNewLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewLoanActionPerformed(evt);
            }
        });

        MLSortByFld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-Z", "Z-A", "Amount Owed Highest-Lowest", "Amount Owed Lowest-Highest", "Interest Highest-Lowest", "Interest Lowest-Highest" }));
        MLSortByFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLSortByFldActionPerformed(evt);
            }
        });

        MLSortTitle.setText("Sort By:");

        MLPayBtn.setText("Make a Payment");
        MLPayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLPayBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Double Click Any Loan in the List Below To View Further Loan Details ");

        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        loanML.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(loanML);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MLTItleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addNewLoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(MLPayBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(logOutBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MLSortByFld, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MLSortTitle))))
                .addGap(15, 15, 15))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MLTItleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MLSortTitle)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewLoan)
                    .addComponent(MLSortByFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MLPayBtn)
                    .addComponent(logOutBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewLoanActionPerformed

        this.setVisible(false); // only if you want the master list to disappear   
        // this is required to pass the account to the create loan UI and will
        //  be required every time a new window opens, otherwise things will break
        CreateLoanUI createLoanUI = new CreateLoanUI();
        createLoanUI.setAccount(account);
        createLoanUI.setVisible(true);
    }//GEN-LAST:event_addNewLoanActionPerformed

    private void MLSortByFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLSortByFldActionPerformed
        //a to z sort
        if (MLSortByFld.getSelectedIndex() == 0)
        {
            model.setLoans(model.azLoans());
            model.fireTableDataChanged();
        }
        
        //reversed a to z sort
        if (MLSortByFld.getSelectedIndex() == 1)
        {
            model.setLoans(model.zaLoans());
            model.fireTableDataChanged();
        }
        
        //Amount owed high to low sort  
        if (MLSortByFld.getSelectedIndex() == 2)
        {
            model.setLoans(model.azAmountLoans());
            model.fireTableDataChanged();
        }
        
        //amount owed low to high sort
        if (MLSortByFld.getSelectedIndex() == 3)
        {
            model.setLoans(model.azAmountLoans());
            model.fireTableDataChanged();
        }
        
        //interest high to low sort
        if (MLSortByFld.getSelectedIndex() == 4)
        {
            model.setLoans(model.azInterestLoans());
            model.fireTableDataChanged();
        }
        
        //interest low to high sort
        if (MLSortByFld.getSelectedIndex() == 5)
        {
            model.setLoans(model.zaInterestLoans());
            model.fireTableDataChanged();
        }  
    }//GEN-LAST:event_MLSortByFldActionPerformed

    private void MLPayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLPayBtnActionPerformed
        PaymentUI pay = new PaymentUI();
        pay.setAccount(account);
        this.setVisible(false);
        pay.setVisible(true);
        
    }//GEN-LAST:event_MLPayBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        this.setVisible(false);
        new LoginUI().setVisible(true);
        
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanMasterListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanMasterListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanMasterListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanMasterListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanMasterListUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MLPayBtn;
    private javax.swing.JComboBox<String> MLSortByFld;
    private javax.swing.JLabel MLSortTitle;
    private javax.swing.JLabel MLTItleBar;
    private javax.swing.JButton addNewLoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loanML;
    private javax.swing.JButton logOutBtn;
    // End of variables declaration//GEN-END:variables
}
